;;; -*- Mode: Common-Lisp; Syntax: Common-Lisp; Package: CL-USER; Base: 10 -*-

;;; Copyright (C) Antonio Menezes Leitao Created on Fri Apr 16 17:36:12 2004
;;; Copyright (C) eValuator, Lda

;;; THIS SOFTWARE IS PROVIDED BY THE AUTHOR 'AS IS' AND ANY EXPRESSED
;;; OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
;;; WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;;; ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
;;; DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
;;; DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
;;; GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;;; INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
;;; WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
;;; NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
;;; SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

(in-package "CL-USER")

(defpackage "LINJ"
   (:use "COMMON-LISP")
   (:export "LINJ2JAVA" 
	    "LINJ2JAVA-DIRECTORY"
	    "WITH-LINJ-SYNTAX"
	    "*LINJ-READTABLE*"
	    ;;These are necessary so that format can use them without package concerns
	    "UNLINJ-NAME"
	    "UNLINJ-TYPE"
	    "PP"
	    "PPEXP"
	    "PPMULTIARGS"
	    "PPSTM"
	    "PPBLK"
	    "PPINIT"
	    "WRITE-OPTIONS"))

;;Import symbols into COMMON-LISP-USER
(eval-when (:load-toplevel)
  (use-package "LINJ"))
